config/routes.rb
Rails.application.routes.draw do
  get 'follwer_users/show'

  get 'following_users/show'

  get 'users/edit'

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :following_users, only: [:show]
  resources :follower_users, only: [:show]
  resources :favorite_relations, only: [:create, :destroy]
  resources :favorite_microposts, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :microposts
    
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  validates :country, length: { maximum: 50 }
  validates :profile, length: { maximum: 150 }
  
  #お気に入り
  has_many :favorite_relations, class_name: "FavoriteRelation",
                                foreign_key: "user_id",
                                dependent: :destroy
  has_many :favorite_microposts, through: :favorite_relations, source: :micropost
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  #メッセージをお気に入り登録する
  def fav(micropost)
    favorite_relations.find_or_create_by(micropost_id: micropost.id)
  end
  
  #お気に入り解除
  def unfav(micropost)
    favorite_relation = favorite_relations.find_by(micropost_id: micropost.id)
    favorite_relation.destroy if favorite_relation
  end
  
  #お気に入りしているかどうか？
  def fav?(micropost)
    favorite_microposts.include?(micropost)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,  only: [:show, :edit, :update]
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :authenticate!, only: [:edit, :update]
  
  
  def show
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  def new
    @user = User.new
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      action_success
    else
     render "edit"
    end
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render "new"
    end
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  def favorite_microposts
    Micropost.where(user_id: user_params[:id])
  end

  
  private

  # get parameters for sinup
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # get parameters for profile editing
  def user_profile
    params.require(:user).permit(:name, :email, :profile, :country, :password, :password_confirmation)
  end

  # get a user instance with :id parameter
  def set_user
    @user = User.find(params[:id])
  end

  # check current_user is editing self ?
  def authenticate!
    if @user != current_user
      redirect_to root_url, flash: { danger: "不正なアクセス" }
    end
  end
  
  def action_success
    redirect_to @user, flash: {success: 'Yes!! Success'}
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>プロフィールを編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render './shared/error_messages', object: f.object %>
        
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control'  %>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control'  %>
       
        <%= f.label :country %>
        <%= f.text_field :country, class: 'form-control'  %>
       
        <%= f.label :profile %>
        <%= f.text_area :profile, class: 'form-control'  %>
        
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      
        <%= f.submit "完了", class: "btn btn-large btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <h1>country:<%= @user.country %></h1>
      <p><%= @user.profile %></p>
      <%= link_to "followers", follower_user_path(@user.id), class: "btn btn-info btn-sm", type:"button"%>
      <%= link_to "followings", following_user_path(@user.id),class: "btn btn-info btn-sm", type:"button"  %>
      <%= link_to "favs", favorite_micropost_path(@user.id),class: "btn btn-info btn-sm", type:"button"%>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>